version: '3'

services:
  api:
    container_name: api
    build: ./api
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:admin@mysql:3306/db_holiday_manager
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=db_holiday_manager
    ports:
      - '3306:3306'

  app:
    container_name: app
    build: .
    ports:
      - '5173:5173'
    depends_on:
      - api
